'use client';

import { useState } from 'react';
import Link from 'next/link';
import { Database } from '@/types/supabase';

// Workshop constants
const WORKSHOP_TITLE = 'Shopify kick start: How to build Shopify stores';
const WORKSHOP_DATE = 'Tuesday, April 21, 2026';
const WORKSHOP_TIME = '09:00 PM Cairo Time';
const WORKSHOP_MODE = 'Live Online on Google Meet';

type Registration = Database['public']['Tables']['workshop_registrations']['Row'];

interface TicketClientPageProps {
    data: Registration;
    pageUrl: string;
}

export default function TicketClientPage({ data, pageUrl }: TicketClientPageProps) {
    const [copied, setCopied] = useState(false);
    const [imageLoading, setImageLoading] = useState(true);
    const [imageError, setImageError] = useState(false);
    const [downloading, setDownloading] = useState(false);

    const posterUrl = data.poster_url;

    // Use the custom caption if generated by the backend, or fallback
    const domainUrl = 'https://muhammedmekky.com/workshop';
    const shareText = data.caption || `I am attending ${WORKSHOP_TITLE} (100% FREE) on ${WORKSHOP_DATE} at ${WORKSHOP_TIME}. If you want to learn how to build high converting Shopify stores step by step over 4 hours, join us: ${domainUrl} #Shopify #Ecommerce #WebDesign`;

    const handleCopyText = () => {
        navigator.clipboard.writeText(shareText);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const openShare = (url: string) => {
        window.open(url, '_blank', 'noopener,noreferrer,width=600,height=600');
    };

    const handleShareLinkedIn = () => {
        openShare(`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(domainUrl)}`);
    };

    const handleShareFacebook = () => {
        openShare(`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(domainUrl)}&quote=${encodeURIComponent(shareText)}`);
    };

    const handleShareTwitter = () => {
        const tweetText = `${shareText}\n\n`;
        openShare(`https://twitter.com/intent/tweet?text=${encodeURIComponent(tweetText)}&url=${encodeURIComponent(domainUrl)}`);
    };

    const handleShareWhatsApp = () => {
        openShare(`https://wa.me/?text=${encodeURIComponent(shareText)}`);
    };

    const handleDownloadPoster = async () => {
        if (!posterUrl) return;
        setDownloading(true);
        try {
            const response = await fetch(posterUrl);
            if (!response.ok) throw new Error('Network response was not ok');
            const blob = await response.blob();
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            const safeName = data.full_name?.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'attendee';
            a.download = `workshop-${safeName}.png`;
            document.body.appendChild(a);
            a.click();
            window.URL.revokeObjectURL(url);
            document.body.removeChild(a);
        } catch (err) {
            console.error('Download failed:', err);
            alert('Could not download the poster. Please click the image to open it directly and save it.');
        } finally {
            setDownloading(false);
        }
    };

    return (
        <main style={{ minHeight: '100vh', backgroundColor: '#0f172a', color: '#fff', fontFamily: 'system-ui, sans-serif', padding: '2rem 1rem' }}>
            <div style={{ maxWidth: '800px', margin: '0 auto' }}>

                <div style={{ textAlign: 'center', marginBottom: '3rem' }}>
                    <div style={{ fontSize: '4rem', marginBottom: '1rem' }}>🎉</div>
                    <h1 style={{ fontSize: '2.5rem', fontWeight: 800, marginBottom: '0.5rem', color: '#fb923c' }}>
                        Booking Confirmed!
                    </h1>
                    <p style={{ fontSize: '1.1rem', color: '#94a3b8' }}>
                        We can&apos;t wait to see you inside, {data.full_name}. Check your email for details.
                    </p>
                </div>

                <div style={{ background: '#1e293b', borderRadius: '1rem', padding: '2rem', border: '1px solid #334155', marginBottom: '2rem' }}>
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', marginBottom: '1.5rem' }}>
                        <span style={{ fontSize: '1.5rem' }}>📢</span>
                        <h2 style={{ fontSize: '1.5rem', fontWeight: 700 }}>Share Your Attendance</h2>
                    </div>

                    <p style={{ fontSize: '0.9rem', color: '#cbd5e1', textAlign: 'center', marginBottom: '1.5rem' }}>
                        When you share this link on social media, your personalized poster will automatically appear!
                    </p>

                    <div style={{ width: '100%', aspectRatio: '1', borderRadius: '0.75rem', overflow: 'hidden', border: '2px solid #334155', marginBottom: '1.5rem', position: 'relative', background: '#0f172a' }}>
                        {imageLoading && (
                            <div style={{ position: 'absolute', inset: 0, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: '1rem' }}>
                                <div style={{ width: '40px', height: '40px', border: '3px solid #334155', borderTopColor: '#fb923c', borderRadius: '50%', animation: 'spin 1s linear infinite' }} />
                                <p style={{ color: '#94a3b8' }}>Generating your personalized poster...</p>
                            </div>
                        )}
                        {imageError && (
                            <div style={{ position: 'absolute', inset: 0, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: '1rem', color: '#ef4444', background: '#0f172a', zIndex: 10 }}>
                                <span>⚠️ Could not load poster</span>
                                <a href={posterUrl} target="_blank" rel="noopener noreferrer" style={{ color: '#fb923c', fontSize: '0.875rem' }}>
                                    Try opening directly
                                </a>
                            </div>
                        )}
                        {posterUrl ? (
                            <a href={posterUrl} target="_blank" rel="noopener noreferrer" style={{ display: 'block', width: '100%', height: '100%' }}>
                                <img
                                    src={posterUrl}
                                    alt="Share Poster"
                                    style={{ width: '100%', height: '100%', objectFit: 'cover', opacity: (imageLoading || imageError) ? 0 : 1, transition: 'opacity 0.5s ease' }}
                                    onLoad={() => setImageLoading(false)}
                                    onError={() => {
                                        setImageLoading(false);
                                        setImageError(true);
                                    }}
                                />
                            </a>
                        ) : null}
                    </div>

                    <div style={{ marginBottom: '1.5rem' }}>
                        <label style={{ display: 'block', fontSize: '0.875rem', fontWeight: 600, color: '#e2e8f0', marginBottom: '0.5rem' }}>Caption Text</label>
                        <div style={{ position: 'relative' }}>
                            <textarea
                                readOnly
                                value={shareText}
                                style={{ width: '100%', height: '120px', background: '#0f172a', border: '1px solid #334155', borderRadius: '0.5rem', padding: '1rem', color: '#cbd5e1', fontSize: '0.875rem', resize: 'none' }}
                            />
                            <button
                                onClick={handleCopyText}
                                style={{ position: 'absolute', top: '0.5rem', right: '0.5rem', background: '#3b82f6', color: '#fff', border: 'none', padding: '0.375rem 0.75rem', borderRadius: '0.375rem', fontSize: '0.75rem', fontWeight: 600, cursor: 'pointer' }}
                            >
                                {copied ? 'Copied!' : 'Copy Text'}
                            </button>
                        </div>
                    </div>

                    <button
                        onClick={handleDownloadPoster}
                        disabled={downloading || imageLoading || !posterUrl}
                        style={{ width: '100%', padding: '1rem', background: '#fb923c', color: '#fff', fontWeight: 700, borderRadius: '0.5rem', border: 'none', cursor: (downloading || imageLoading || !posterUrl) ? 'not-allowed' : 'pointer', opacity: (downloading || imageLoading || !posterUrl) ? 0.7 : 1, marginBottom: '1.5rem', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem' }}
                    >
                        <span>📥</span> {downloading ? 'Downloading...' : 'Download Poster Image'}
                    </button>

                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))', gap: '0.75rem' }}>
                        <button onClick={handleShareLinkedIn} style={{ background: '#0077b5', color: '#fff', padding: '0.75rem', borderRadius: '0.5rem', border: 'none', cursor: 'pointer', fontWeight: 600, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem' }}>
                            LinkedIn
                        </button>
                        <button onClick={handleShareFacebook} style={{ background: '#1877f2', color: '#fff', padding: '0.75rem', borderRadius: '0.5rem', border: 'none', cursor: 'pointer', fontWeight: 600, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem' }}>
                            Facebook
                        </button>
                        <button onClick={handleShareTwitter} style={{ background: '#000', color: '#fff', padding: '0.75rem', borderRadius: '0.5rem', border: '1px solid #334155', cursor: 'pointer', fontWeight: 600, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem' }}>
                            Twitter (X)
                        </button>
                        <button onClick={handleShareWhatsApp} style={{ background: '#25d366', color: '#fff', padding: '0.75rem', borderRadius: '0.5rem', border: 'none', cursor: 'pointer', fontWeight: 600, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem' }}>
                            WhatsApp
                        </button>
                    </div>
                </div>

                <div style={{ background: '#1e293b', borderRadius: '1rem', padding: '2rem', border: '1px solid #334155', marginBottom: '2rem' }}>
                    <h2 style={{ fontSize: '1.25rem', fontWeight: 700, marginBottom: '1.5rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                        <span>📅</span> Your Booking Details
                    </h2>

                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem' }}>
                        <div>
                            <p style={{ fontSize: '0.875rem', color: '#94a3b8', marginBottom: '0.25rem' }}>Name</p>
                            <p style={{ fontWeight: 600 }}>{data.full_name}</p>
                            {data.job_title && <p style={{ fontSize: '0.875rem', color: '#cbd5e1' }}>{data.job_title}</p>}
                        </div>
                        <div>
                            <p style={{ fontSize: '0.875rem', color: '#94a3b8', marginBottom: '0.25rem' }}>Date & Time</p>
                            <p style={{ fontWeight: 600 }}>{WORKSHOP_DATE}</p>
                            <p style={{ fontSize: '0.875rem', color: '#cbd5e1' }}>{WORKSHOP_TIME}</p>
                        </div>
                        <div>
                            <p style={{ fontSize: '0.875rem', color: '#94a3b8', marginBottom: '0.25rem' }}>Location</p>
                            <p style={{ fontWeight: 600 }}>{WORKSHOP_MODE}</p>
                        </div>
                    </div>
                </div>

                <div style={{ textAlign: 'center' }}>
                    <Link href="/workshop" style={{ color: '#fb923c', textDecoration: 'none', fontWeight: 600 }}>
                        ← Back to Workshop Details
                    </Link>
                </div>

                <style dangerouslySetInnerHTML={{
                    __html: `
                    @keyframes spin {
                        to { transform: rotate(360deg); }
                    }
                `}} />
            </div>
        </main>
    );
}
